/* tslint:disable */
/* eslint-disable */
/**
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../../base';
// @ts-ignore
import type { ProblemDetails } from '../../src/models';
// @ts-ignore
import type { Receive } from '../../src/models';
/**
 * ReceiveApi - axios parameter creator
 * @export
 */
export const ReceiveApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary List incoming invoices
         * @param {number} [companyId] Company id.
         * @param {string} [identifier] SDI identifier.
         * @param {boolean} [unread] Unread items only.
         * @param {string} [committente] VAT number or fiscal code.
         * @param {string} [prestatore] VAT number or fiscal code.
         * @param {string} [fileName] File name.
         * @param {string} [lastUpdateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [lastUpdateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentNumber] Document number.
         * @param {number} [page] Page number.
         * @param {number} [pageSize] Items per page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveGet: async (companyId?: number, identifier?: string, unread?: boolean, committente?: string, prestatore?: string, fileName?: string, lastUpdateFrom?: string, lastUpdateTo?: string, dateSentFrom?: string, dateSentTo?: string, documentDateFrom?: string, documentDateTo?: string, documentNumber?: string, page?: number, pageSize?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/invoice/v1/receive`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)

            if (companyId !== undefined) {
                localVarQueryParameter['company_id'] = companyId;
            }

            if (identifier !== undefined) {
                localVarQueryParameter['identifier'] = identifier;
            }

            if (unread !== undefined) {
                localVarQueryParameter['unread'] = unread;
            }

            if (committente !== undefined) {
                localVarQueryParameter['committente'] = committente;
            }

            if (prestatore !== undefined) {
                localVarQueryParameter['prestatore'] = prestatore;
            }

            if (fileName !== undefined) {
                localVarQueryParameter['file_name'] = fileName;
            }

            if (lastUpdateFrom !== undefined) {
                localVarQueryParameter['last_update_from'] = (lastUpdateFrom as any instanceof Date) ?
                    (lastUpdateFrom as any).toISOString() :
                    lastUpdateFrom;
            }

            if (lastUpdateTo !== undefined) {
                localVarQueryParameter['last_update_to'] = (lastUpdateTo as any instanceof Date) ?
                    (lastUpdateTo as any).toISOString() :
                    lastUpdateTo;
            }

            if (dateSentFrom !== undefined) {
                localVarQueryParameter['date_sent_from'] = (dateSentFrom as any instanceof Date) ?
                    (dateSentFrom as any).toISOString() :
                    dateSentFrom;
            }

            if (dateSentTo !== undefined) {
                localVarQueryParameter['date_sent_to'] = (dateSentTo as any instanceof Date) ?
                    (dateSentTo as any).toISOString() :
                    dateSentTo;
            }

            if (documentDateFrom !== undefined) {
                localVarQueryParameter['document_date_from'] = (documentDateFrom as any instanceof Date) ?
                    (documentDateFrom as any).toISOString() :
                    documentDateFrom;
            }

            if (documentDateTo !== undefined) {
                localVarQueryParameter['document_date_to'] = (documentDateTo as any instanceof Date) ?
                    (documentDateTo as any).toISOString() :
                    documentDateTo;
            }

            if (documentNumber !== undefined) {
                localVarQueryParameter['document_number'] = documentNumber;
            }

            if (page !== undefined) {
                localVarQueryParameter['page'] = page;
            }

            if (pageSize !== undefined) {
                localVarQueryParameter['page_size'] = pageSize;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Delete an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveIdDelete: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('invoiceV1ReceiveIdDelete', 'id', id)
            const localVarPath = `/invoice/v1/receive/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Get an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveIdGet: async (id: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('invoiceV1ReceiveIdGet', 'id', id)
            const localVarPath = `/invoice/v1/receive/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Basic required
            // http basic authentication required
            setBasicAuthToObject(localVarRequestOptions, configuration)


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReceiveApi - functional programming interface
 * @export
 */
export const ReceiveApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReceiveApiAxiosParamCreator(configuration)
    return {
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary List incoming invoices
         * @param {number} [companyId] Company id.
         * @param {string} [identifier] SDI identifier.
         * @param {boolean} [unread] Unread items only.
         * @param {string} [committente] VAT number or fiscal code.
         * @param {string} [prestatore] VAT number or fiscal code.
         * @param {string} [fileName] File name.
         * @param {string} [lastUpdateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [lastUpdateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentNumber] Document number.
         * @param {number} [page] Page number.
         * @param {number} [pageSize] Items per page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invoiceV1ReceiveGet(companyId?: number, identifier?: string, unread?: boolean, committente?: string, prestatore?: string, fileName?: string, lastUpdateFrom?: string, lastUpdateTo?: string, dateSentFrom?: string, dateSentTo?: string, documentDateFrom?: string, documentDateTo?: string, documentNumber?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Receive>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invoiceV1ReceiveGet(companyId, identifier, unread, committente, prestatore, fileName, lastUpdateFrom, lastUpdateTo, dateSentFrom, dateSentTo, documentDateFrom, documentDateTo, documentNumber, page, pageSize, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReceiveApi.invoiceV1ReceiveGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Delete an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invoiceV1ReceiveIdDelete(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Receive>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invoiceV1ReceiveIdDelete(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReceiveApi.invoiceV1ReceiveIdDelete']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Get an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async invoiceV1ReceiveIdGet(id: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Receive>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.invoiceV1ReceiveIdGet(id, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReceiveApi.invoiceV1ReceiveIdGet']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReceiveApi - factory interface
 * @export
 */
export const ReceiveApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReceiveApiFp(configuration)
    return {
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary List incoming invoices
         * @param {number} [companyId] Company id.
         * @param {string} [identifier] SDI identifier.
         * @param {boolean} [unread] Unread items only.
         * @param {string} [committente] VAT number or fiscal code.
         * @param {string} [prestatore] VAT number or fiscal code.
         * @param {string} [fileName] File name.
         * @param {string} [lastUpdateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [lastUpdateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [dateSentTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentDateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
         * @param {string} [documentNumber] Document number.
         * @param {number} [page] Page number.
         * @param {number} [pageSize] Items per page.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveGet(companyId?: number, identifier?: string, unread?: boolean, committente?: string, prestatore?: string, fileName?: string, lastUpdateFrom?: string, lastUpdateTo?: string, dateSentFrom?: string, dateSentTo?: string, documentDateFrom?: string, documentDateTo?: string, documentNumber?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Receive>> {
            return localVarFp.invoiceV1ReceiveGet(companyId, identifier, unread, committente, prestatore, fileName, lastUpdateFrom, lastUpdateTo, dateSentFrom, dateSentTo, documentDateFrom, documentDateTo, documentNumber, page, pageSize, options).then((request) => request(axios, basePath));
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Delete an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Receive> {
            return localVarFp.invoiceV1ReceiveIdDelete(id, options).then((request) => request(axios, basePath));
        },
        /**
         * Receive invoices are the invoices that are received from other companies.
         * @summary Get an incoming invoice by id
         * @param {number} id Item id.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        invoiceV1ReceiveIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Receive> {
            return localVarFp.invoiceV1ReceiveIdGet(id, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ReceiveApi - interface
 * @export
 * @interface ReceiveApi
 */
export interface ReceiveApiInterface {
    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary List incoming invoices
     * @param {number} [companyId] Company id.
     * @param {string} [identifier] SDI identifier.
     * @param {boolean} [unread] Unread items only.
     * @param {string} [committente] VAT number or fiscal code.
     * @param {string} [prestatore] VAT number or fiscal code.
     * @param {string} [fileName] File name.
     * @param {string} [lastUpdateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [lastUpdateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [dateSentFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [dateSentTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentDateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentDateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentNumber] Document number.
     * @param {number} [page] Page number.
     * @param {number} [pageSize] Items per page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApiInterface
     */
    invoiceV1ReceiveGet(companyId?: number, identifier?: string, unread?: boolean, committente?: string, prestatore?: string, fileName?: string, lastUpdateFrom?: string, lastUpdateTo?: string, dateSentFrom?: string, dateSentTo?: string, documentDateFrom?: string, documentDateTo?: string, documentNumber?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig): AxiosPromise<Array<Receive>>;

    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary Delete an incoming invoice by id
     * @param {number} id Item id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApiInterface
     */
    invoiceV1ReceiveIdDelete(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Receive>;

    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary Get an incoming invoice by id
     * @param {number} id Item id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApiInterface
     */
    invoiceV1ReceiveIdGet(id: number, options?: RawAxiosRequestConfig): AxiosPromise<Receive>;

}

/**
 * ReceiveApi - object-oriented interface
 * @export
 * @class ReceiveApi
 * @extends {BaseAPI}
 */
export class ReceiveApi extends BaseAPI implements ReceiveApiInterface {
    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary List incoming invoices
     * @param {number} [companyId] Company id.
     * @param {string} [identifier] SDI identifier.
     * @param {boolean} [unread] Unread items only.
     * @param {string} [committente] VAT number or fiscal code.
     * @param {string} [prestatore] VAT number or fiscal code.
     * @param {string} [fileName] File name.
     * @param {string} [lastUpdateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [lastUpdateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [dateSentFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [dateSentTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentDateFrom] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentDateTo] UTC ISO 8601 (2024-11-29T12:34:56Z)
     * @param {string} [documentNumber] Document number.
     * @param {number} [page] Page number.
     * @param {number} [pageSize] Items per page.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApi
     */
    public invoiceV1ReceiveGet(companyId?: number, identifier?: string, unread?: boolean, committente?: string, prestatore?: string, fileName?: string, lastUpdateFrom?: string, lastUpdateTo?: string, dateSentFrom?: string, dateSentTo?: string, documentDateFrom?: string, documentDateTo?: string, documentNumber?: string, page?: number, pageSize?: number, options?: RawAxiosRequestConfig) {
        return ReceiveApiFp(this.configuration).invoiceV1ReceiveGet(companyId, identifier, unread, committente, prestatore, fileName, lastUpdateFrom, lastUpdateTo, dateSentFrom, dateSentTo, documentDateFrom, documentDateTo, documentNumber, page, pageSize, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary Delete an incoming invoice by id
     * @param {number} id Item id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApi
     */
    public invoiceV1ReceiveIdDelete(id: number, options?: RawAxiosRequestConfig) {
        return ReceiveApiFp(this.configuration).invoiceV1ReceiveIdDelete(id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Receive invoices are the invoices that are received from other companies.
     * @summary Get an incoming invoice by id
     * @param {number} id Item id.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof ReceiveApi
     */
    public invoiceV1ReceiveIdGet(id: number, options?: RawAxiosRequestConfig) {
        return ReceiveApiFp(this.configuration).invoiceV1ReceiveIdGet(id, options).then((request) => request(this.axios, this.basePath));
    }
}

