/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DatiBollo } from './dati-bollo';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiCassaPrevidenziale } from './dati-cassa-previdenziale';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiRitenuta } from './dati-ritenuta';
// May contain unused imports in some cases
// @ts-ignore
import type { ScontoMaggiorazione } from './sconto-maggiorazione';

export interface DatiGeneraliDocumento {
    'tipo_documento'?: string | null;
    'divisa'?: string | null;
    'data'?: string;
    'numero'?: string | null;
    'dati_ritenuta'?: Array<DatiRitenuta> | null;
    'dati_bollo'?: DatiBollo;
    'dati_cassa_previdenziale'?: Array<DatiCassaPrevidenziale> | null;
    'sconto_maggiorazione'?: Array<ScontoMaggiorazione> | null;
    'importo_totale_documento'?: number | null;
    'arrotondamento'?: number | null;
    'causale'?: Array<string> | null;
    'art73'?: string | null;
}

