/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DatiAnagraficiVettore } from './dati-anagrafici-vettore';
// May contain unused imports in some cases
// @ts-ignore
import type { IndirizzoResa } from './indirizzo-resa';

export interface DatiTrasporto {
    'dati_anagrafici_vettore'?: DatiAnagraficiVettore;
    'mezzo_trasporto'?: string | null;
    'causale_trasporto'?: string | null;
    'numero_colli'?: number | null;
    'descrizione'?: string | null;
    'unita_misura_peso'?: string | null;
    'peso_lordo'?: number | null;
    'peso_netto'?: number | null;
    'data_ora_ritiro'?: string | null;
    'data_inizio_trasporto'?: string | null;
    'tipo_resa'?: string | null;
    'indirizzo_resa'?: IndirizzoResa;
    'data_ora_consegna'?: string | null;
}

