/* tslint:disable */
/* eslint-disable */
/**
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. The API also provides advanced features as encryption at rest, invoice validation, multiple upload formats, webhooks, event logging, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DatiCassaPrevidenziale
 */
export interface DatiCassaPrevidenziale {
    /**
     * 
     * @type {string}
     * @memberof DatiCassaPrevidenziale
     */
    'tipo_cassa'?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DatiCassaPrevidenziale
     */
    'al_cassa'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatiCassaPrevidenziale
     */
    'importo_contributo_cassa'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatiCassaPrevidenziale
     */
    'imponibile_cassa'?: number;
    /**
     * 
     * @type {number}
     * @memberof DatiCassaPrevidenziale
     */
    'aliquota_iva'?: number;
    /**
     * 
     * @type {string}
     * @memberof DatiCassaPrevidenziale
     */
    'ritenuta'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DatiCassaPrevidenziale
     */
    'natura'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DatiCassaPrevidenziale
     */
    'riferimento_amministrazione'?: string | null;
}

