/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { AltriDatiGestionali } from './altri-dati-gestionali';
// May contain unused imports in some cases
// @ts-ignore
import type { CodiceArticolo } from './codice-articolo';
// May contain unused imports in some cases
// @ts-ignore
import type { ScontoMaggiorazione } from './sconto-maggiorazione';

export interface DettaglioLinee {
    'numero_linea'?: number;
    'tipo_cessione_prestazione'?: string | null;
    'codice_articolo'?: Array<CodiceArticolo> | null;
    'descrizione'?: string | null;
    'quantita'?: number | null;
    'unita_misura'?: string | null;
    'data_inizio_periodo'?: string | null;
    'data_fine_periodo'?: string | null;
    'prezzo_unitario'?: number;
    'sconto_maggiorazione'?: Array<ScontoMaggiorazione> | null;
    'prezzo_totale'?: number;
    'aliquota_iva'?: number;
    'ritenuta'?: string | null;
    'natura'?: string | null;
    'riferimento_amministrazione'?: string | null;
    'altri_dati_gestionali'?: Array<AltriDatiGestionali> | null;
}

