/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface DettaglioPagamento {
    'beneficiario'?: string | null;
    'modalita_pagamento'?: string | null;
    'data_riferimento_termini_pagamento'?: string | null;
    'giorni_termini_pagamento'?: number | null;
    'data_scadenza_pagamento'?: string | null;
    'importo_pagamento'?: number;
    'cod_ufficio_postale'?: string | null;
    'cognome_quietanzante'?: string | null;
    'nome_quietanzante'?: string | null;
    'cf_quietanzante'?: string | null;
    'titolo_quietanzante'?: string | null;
    'istituto_finanziario'?: string | null;
    'iban'?: string | null;
    'abi'?: string | null;
    'cab'?: string | null;
    'bic'?: string | null;
    'sconto_pagamento_anticipato'?: number | null;
    'data_limite_pagamento_anticipato'?: string | null;
    'penalita_pagamenti_ritardati'?: number | null;
    'data_decorrenza_penale'?: string | null;
    'codice_pagamento'?: string | null;
}

