/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Event {
    /**
     * Unique identifier. Leave it at 0 for new records as it will be set automatically.
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     */
    'version'?: number;
    /**
     * User id.
     */
    'user_id'?: number;
    /**
     * Api key id.
     */
    'api_key_id'?: number;
    /**
     * Company id.
     */
    'company_id'?: number | null;
    /**
     * Request method.
     */
    'method'?: string | null;
    /**
     * API endpoint.
     */
    'endpoint'?: string | null;
    /**
     * Api version.
     */
    'api_version'?: number;
    /**
     * Status code returned by the API.
     */
    'status_code'?: number;
    /**
     * Date and time of the request.
     */
    'date_time'?: string;
    /**
     * Response error.
     */
    'error'?: string | null;
    /**
     * ID of the resource created or modified by this request.
     */
    'resource_id'?: number | null;
    /**
     * Wether the request was successful.
     */
    'success'?: boolean;
    /**
     * Request query. Only used for internal logging, not sent to webhooks.
     */
    'query'?: string | null;
    /**
     * Response payload. It is guaranteed to be cyphered at rest.
     */
    'response_body'?: string | null;
}

