/* tslint:disable */
/* eslint-disable */
/**
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Allegati } from './allegati';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiBeniServizi } from './dati-beni-servizi';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiGenerali } from './dati-generali';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiPagamento } from './dati-pagamento';
// May contain unused imports in some cases
// @ts-ignore
import type { DatiVeicoli } from './dati-veicoli';

/**
 * 
 * @export
 * @interface FatturaElettronicaBody
 */
export interface FatturaElettronicaBody {
    /**
     * 
     * @type {DatiGenerali}
     * @memberof FatturaElettronicaBody
     */
    'dati_generali'?: DatiGenerali;
    /**
     * 
     * @type {DatiBeniServizi}
     * @memberof FatturaElettronicaBody
     */
    'dati_beni_servizi'?: DatiBeniServizi;
    /**
     * 
     * @type {DatiVeicoli}
     * @memberof FatturaElettronicaBody
     */
    'dati_veicoli'?: DatiVeicoli;
    /**
     * 
     * @type {Array<DatiPagamento>}
     * @memberof FatturaElettronicaBody
     */
    'dati_pagamento'?: Array<DatiPagamento> | null;
    /**
     * 
     * @type {Array<Allegati>}
     * @memberof FatturaElettronicaBody
     */
    'allegati'?: Array<Allegati> | null;
}

