/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SendReduced } from './send-reduced';

export interface Update {
    /**
     * Unique identifier. Leave it at 0 for new records as it will be set automatically.
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     */
    'version'?: number;
    /**
     * User id.
     */
    'user_id'?: number;
    /**
     * Company id.
     */
    'company_id'?: number;
    /**
     * Send id. This is the id of the sent invoice to which this update refers to.
     */
    'send_id'?: number;
    /**
     * Last update from SDI.
     */
    'last_update'?: string;
    /**
     * State of the document. Theses are the possible values, as per the SDI documentation:
     */
    'state'?: UpdateStateEnum;
    /**
     * Description for the state.
     */
    'description'?: string | null;
    /**
     * SDI message id.
     */
    'message_id'?: string | null;
    /**
     * SDI errors, if any.
     */
    'errors'?: Array<Error> | null;
    /**
     * Wether the item has been read at least once.
     */
    'is_read'?: boolean;
    'send'?: SendReduced;
}

export const UpdateStateEnum = {
    Inviato: 'Inviato',
    Consegnato: 'Consegnato',
    NonConsegnato: 'NonConsegnato',
    Scartato: 'Scartato',
    AccettatoDalDestinatario: 'AccettatoDalDestinatario',
    RifiutatoDalDestinatario: 'RifiutatoDalDestinatario',
    ImpossibilitaDiRecapito: 'ImpossibilitaDiRecapito',
    DecorrenzaTermini: 'DecorrenzaTermini',
    AttestazioneTrasmissioneFattura: 'AttestazioneTrasmissioneFattura'
} as const;

export type UpdateStateEnum = typeof UpdateStateEnum[keyof typeof UpdateStateEnum];


