/* tslint:disable */
/* eslint-disable */
/**
 * Italian eInvoice API
 * The Italian eInvoice API is a RESTful API that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed by Invoicetronic to be simple and easy to use, abstracting away SDI complexity while still providing complete control over the invoice send/receive process. The API also provides advanced features and a rich toolchain, such as invoice validation, multiple upload methods, webhooks, event logs, CORS support, client SDKs for commonly used languages, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WebHook
 */
export interface WebHook {
    /**
     * Unique identifier. Leave it at 0 for new records as it will be set automatically.
     * @type {number}
     * @memberof WebHook
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     * @type {string}
     * @memberof WebHook
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     * @type {number}
     * @memberof WebHook
     */
    'version'?: number;
    /**
     * User id.
     * @type {number}
     * @memberof WebHook
     */
    'user_id'?: number;
    /**
     * Company id.
     * @type {number}
     * @memberof WebHook
     */
    'company_id'?: number | null;
    /**
     * The url of your application\'s endpoint that will receive a POST request when the webhook is fired.
     * @type {string}
     * @memberof WebHook
     */
    'url'?: string | null;
    /**
     * Wetehr the webhooks is enabled or not. On creation, this is set to `true`.
     * @type {boolean}
     * @memberof WebHook
     */
    'enabled'?: boolean;
    /**
     * The secret used to generate webhook signatures, only returned on creation. You should store this value securely and validate it on every call, to ensure that the caller is InvoiceApi.
     * @type {string}
     * @memberof WebHook
     */
    'secret'?: string | null;
    /**
     * An optional description.
     * @type {string}
     * @memberof WebHook
     */
    'description'?: string | null;
    /**
     * List of events to that trigger the webhook.  See InvoiceApi.SupportedEvents.Available for a list of valid event names.
     * @type {Array<string>}
     * @memberof WebHook
     */
    'events'?: Array<string> | null;
}

