/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface WebHook {
    /**
     * Unique identifier. Leave it at 0 for new records as it will be set automatically.
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     */
    'version'?: number;
    /**
     * User id.
     */
    'user_id'?: number;
    /**
     * Company id.
     */
    'company_id'?: number | null;
    /**
     * The url of your application\'s endpoint that will receive a POST request when the webhook is fired.
     */
    'url'?: string | null;
    /**
     * Wether the webhook is enabled. On creation, this is set to `true`.
     */
    'enabled'?: boolean;
    /**
     * The secret used to generate webhook signatures, only returned on creation. You should store this value securely and validate it on every call, to ensure that the caller is InvoicetronicApi.
     */
    'secret'?: string | null;
    /**
     * An optional description.
     */
    'description'?: string | null;
    /**
     * List of events to that trigger the webhook.  See Invoicetronic.SupportedEvents.Available for a list of valid event names.
     */
    'events'?: Array<string> | null;
}

