/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.12.0
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * A webhook subscription.
 */
export interface WebHook {
    /**
     * Unique identifier. For POST requests, leave it at `0` — the server will assign one automatically. For PUT requests, set it to the id of the record you want to update.
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     */
    'version'?: number;
    /**
     * User id. It is set automatically based on the authenticated user.
     */
    'user_id'?: number;
    /**
     * Optional company id. If set, the webhook is restricted to events for that company; if omitted, it fires for all companies on the account.
     */
    'company_id'?: number | null;
    /**
     * The url of your application\'s endpoint that will receive a POST request when the webhook is fired.
     */
    'url': string;
    /**
     * Whether the webhook is enabled. On creation, this is set to `true`.
     */
    'enabled'?: boolean;
    /**
     * The secret used to generate webhook signatures, only returned on creation. You should store this value securely and validate it on every call, to ensure that the caller is InvoicetronicApi.
     */
    'secret'?: string | null;
    /**
     * An optional description.
     */
    'description'?: string | null;
    /**
     * List of events that trigger the webhook. See Invoicetronic.SupportedEvents.Available for a list of valid event names.
     */
    'events'?: Array<string> | null;
    /**
     * Timestamp of the last failure notification email sent for this webhook. Set by the notifier service; reset to null on successful delivery.
     */
    'failure_notified_at'?: string | null;
}

