/* tslint:disable */
/* eslint-disable */
/**
 * Invoicetronic API
 * The [Invoicetronic API][2] is a RESTful service that allows you to send and receive invoices through the Italian [Servizio di Interscambio (SDI)][1], or Interchange Service. The API is designed to be simple and easy to use, abstracting away SDI complexity while providing complete control over the invoice send/receive process. It provides advanced features as encryption at rest, multi-language pre-flight invoice validation, multiple upload formats, webhooks, event logging, client SDKs, and CLI tools.  For more information, see  [Invoicetronic website][2]  [1]: https://www.fatturapa.gov.it/it/sistemainterscambio/cose-il-sdi/ [2]: https://invoicetronic.com/
 *
 * The version of the OpenAPI document: 1.12.0
 * Contact: info@invoicetronic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Webhook history.
 */
export interface WebHookHistory {
    /**
     * Unique identifier. For POST requests, leave it at `0` — the server will assign one automatically. For PUT requests, set it to the id of the record you want to update.
     */
    'id'?: number;
    /**
     * Creation date. It is set automatically.
     */
    'created'?: string;
    /**
     * Row version, for optimistic concurrency. It is set automatically.
     */
    'version'?: number;
    /**
     * Webhook id.
     */
    'web_hook_id'?: number;
    /**
     * User id.
     */
    'user_id'?: number;
    /**
     * Event name.
     */
    'event'?: string | null;
    /**
     * HTTP status code returned by the webhook endpoint. A value of 0 means the request could not be completed due to a network error (e.g., DNS resolution failure, connection refused, or timeout). This typically indicates that the endpoint URL is misconfigured or no longer exists.
     */
    'status_code'?: number;
    /**
     * Error description, if any. Null when the delivery is successful (2xx). Contains the exception message for network errors (status code 0) or the response body for non-2xx HTTP responses.
     */
    'error'?: string | null;
    /**
     * Date and time of the request.
     */
    'date_time'?: string;
    /**
     * Whether the request was successful.
     */
    'success'?: boolean;
}

